### Loops

In [11]:
list1=[10,20,45,90,100]

In [2]:
for i in list1:
    print(i)

10
20
45
90
100


In [3]:
range(2,8)

range(2, 8)

In [5]:
for i in range(2,8,2):
    print(i)

2
4
6


In [6]:
for i in (10,20,30):
    print(i)

10
20
30


In [41]:
for i in {3,20,4}:
    print(i)

3
20
4


In [31]:
{12,9,3,10}

{3, 9, 10, 12}

In [42]:
list1

[10, 20, 45, 90, 100]

In [46]:
# List Comprehension
[i*2 for i in list1]

[20, 40, 90, 180, 200]

In [47]:
[i+2 for i in list1]

[12, 22, 47, 92, 102]

In [48]:
[i-2 for i in list1]

[8, 18, 43, 88, 98]

## while loop

In [3]:
i=1
n=5
sum1=0
while(i<n):
    sum1= sum1+i
    print(sum1)
    i+=1

1
3
6
10


In [4]:
counter=1
while(counter<10):
    print('counter is inside the loop')
    counter+=1
else:
    print('counter is out of the loop')

counter is inside the loop
counter is inside the loop
counter is inside the loop
counter is inside the loop
counter is inside the loop
counter is inside the loop
counter is inside the loop
counter is inside the loop
counter is inside the loop
counter is out of the loop


In [7]:
x=40
if x>10:
    x-=2
    print(x)
elif x<10:
    x+=2
    print(x)
else:
    print(x)

38


In [9]:
x= int(input('Enter the Number'))
if x%2==0:
    print(x,',','Number is Even')
else:
    print(x, ',','Number is odd')

Enter the Number33
33 , Number is odd


In [12]:
list1

[10, 20, 45, 90, 100]

In [14]:
for x in list1:
    if x%2==0:
        print(x,',','Even')
    else:
         print(x, ',','odd')

10 , Even
20 , Even
45 , odd
90 , Even
100 , Even


## Functions

In [15]:
def fun(x):
    return x*x

In [19]:
fun(3)

9

In [20]:
def add(x):
    return x+x

In [21]:
add(10)

20

In [22]:
def mult(x,y):
    return x*y

In [23]:
mult(3,4)

12

In [29]:
def Largest(x,y):
    if x>y:
        return x ,'largest'
    else:
        return y,'largest'

In [31]:
Largest(2,11)

(11, 'largest')

In [34]:
a=[]
odd=[]
even=[]
def fun(a):
    for i in a:
        if i%2==0:
            even.append(i)
        else:
            odd.append(i)
    print(even,odd)

In [35]:
fun([1,3,8,10,22,23])

[8, 10, 22] [1, 3, 23]


## Lambda 

In [36]:
fun= lambda x: x*2

In [37]:
fun(4)

8

In [38]:
fun1= lambda x,y: x*y

In [39]:
fun1(3,4)

12

In [40]:
fun2= lambda x:'even' if x%2==0 else 'odd'

In [42]:
fun2(41)

'odd'

In [43]:
list1

[10, 20, 45, 90, 100]

In [44]:
fun2= lambda x:['even' if x%2==0 else 'odd' for x in list1]

In [47]:
fun2(list1)

['even', 'even', 'odd', 'even', 'even']

In [50]:
list2=[20,23,34]

In [48]:
list1

[10, 20, 45, 90, 100]

In [51]:
list(filter(lambda x: x%2==0,list2))

[20, 34]

In [52]:
def fun(x):
    if x>10:
        return x

In [56]:
fun(1)

In [57]:
list1

[10, 20, 45, 90, 100]

In [58]:
list(filter(fun,list1))

[20, 45, 90, 100]

## Numpy

In [59]:
list1=[10,20,30]
list2=[2,4,6]

In [68]:
list3=[]
for i in range(len(list1)):
    list3.append(list1[i]-list2[i])

In [69]:
list3

[8, 16, 24]

In [70]:
import numpy as np

In [71]:
one_dim= np.array([1,3,4,5,10,20,23])

In [72]:
one_dim

array([ 1,  3,  4,  5, 10, 20, 23])

In [73]:
type(one_dim)

numpy.ndarray

In [74]:
one_dim.ndim

1

In [75]:
one_dim.size

7

In [76]:
one_dim[5]

20

In [77]:
one_dim

array([ 1,  3,  4,  5, 10, 20, 23])

In [79]:
one_dim[2:5]

array([ 4,  5, 10])

In [81]:
np.insert(one_dim,3,50)

array([ 1,  3,  4, 50,  5, 10, 20, 23])

In [82]:
one_dim

array([ 1,  3,  4,  5, 10, 20, 23])

In [94]:
np.where(one_dim==10)[0][0]

4

In [89]:
np.where(one_dim==23)

(array([6], dtype=int64),)

In [95]:
one_dim

array([ 1,  3,  4,  5, 10, 20, 23])

In [97]:
one_dim[4]=100

In [98]:
one_dim

array([  1,   3,   4,   5, 100,  20,  23])

In [100]:
np.delete(one_dim,[3,4])

array([ 1,  3,  4, 20, 23])

## Two_Dimensional_Array

In [101]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [102]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
type(two_dim)

numpy.ndarray

In [104]:
two_dim.ndim

2

In [105]:
two_dim.size

9

In [106]:
two_dim.shape

(3, 3)

In [107]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
two_dim[1,0]

4

In [109]:
two_dim[2,1]

8