In [1]:
import numpy as np

In [2]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
two_dim[2,2]

9

In [5]:
two_dim[0]

array([1, 2, 3])

In [6]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
two_dim[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
two_dim[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [14]:
two_dim[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [15]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.max(two_dim)

9

In [25]:
two_dim.shape

(3, 3)

In [26]:
np.min(two_dim)

1

In [27]:
np.mean(two_dim)

5.0

In [28]:
np.median(two_dim)

5.0

In [29]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.argmax(two_dim)

8

In [31]:
np.argmin(two_dim)

0

In [35]:
two_dim= np.arange(1,17).reshape(4,4)
two_dim

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
two_dim=np.random.randint(0,100,16).reshape(4,4)
two_dim

array([[91, 66, 33, 16],
       [17, 73, 88, 44],
       [11, 19,  8, 62],
       [64,  6, 35, 56]])

In [48]:
two_dim

array([[91, 66, 33, 16],
       [17, 73, 88, 44],
       [11, 19,  8, 62],
       [64,  6, 35, 56]])

In [49]:
a=np.random.randint(0,20,4).reshape(2,2)
a

array([[15, 10],
       [16, 11]])

In [50]:
b=np.random.randint(0,20,4).reshape(2,2)
b

array([[ 6,  6],
       [11, 13]])

In [51]:
a+b

array([[21, 16],
       [27, 24]])

In [52]:
a-b

array([[ 9,  4],
       [ 5, -2]])

In [53]:
a*b

array([[ 90,  60],
       [176, 143]])

In [54]:
a/b

array([[2.5       , 1.66666667],
       [1.45454545, 0.84615385]])

In [55]:
# Matrix Multiplication
a@b

array([[200, 220],
       [217, 239]])

In [56]:
two_dim

array([[91, 66, 33, 16],
       [17, 73, 88, 44],
       [11, 19,  8, 62],
       [64,  6, 35, 56]])

In [57]:
np.unique(two_dim)

array([ 6,  8, 11, 16, 17, 19, 33, 35, 44, 56, 62, 64, 66, 73, 88, 91])

In [60]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
a

array([[15, 10],
       [16, 11]])

In [63]:
eig_values, eig_vectors=np.linalg.eig(a)

In [64]:
eig_values

array([25.80624847,  0.19375153])

In [65]:
eig_vectors

array([[ 0.67919643, -0.55969517],
       [ 0.73395654,  0.82869857]])

In [68]:
np.delete(two_dim,1,axis=1)

array([[91, 33, 16],
       [17, 88, 44],
       [11,  8, 62],
       [64, 35, 56]])

In [69]:
two_dim

array([[91, 66, 33, 16],
       [17, 73, 88, 44],
       [11, 19,  8, 62],
       [64,  6, 35, 56]])

In [71]:
np.sum(two_dim,axis=0)

array([183, 164, 164, 178])

In [72]:
np.mean(two_dim,axis=1)

array([51.5 , 55.5 , 25.  , 40.25])

## Pandas

In [73]:
import pandas as pd

### Series

In [78]:
ser= pd.Series(data=[90,100,89,100,68],index=['Ajay','Sanjay','Ramya','Suman','John'])
ser

Ajay       90
Sanjay    100
Ramya      89
Suman     100
John       68
dtype: int64

In [110]:
ser.ndim

1

In [81]:
ser['Sanjay':'Ramya']

Sanjay    100
Ramya      89
dtype: int64

In [82]:
ser[['Ajay','Ramya','John']]

Ajay     90
Ramya    89
John     68
dtype: int64

In [83]:
ser.max()

100

In [84]:
ser.min()

68

In [85]:
ser.median()

90.0

In [86]:
ser.mode()

0    100
dtype: int64

In [88]:
ser[ser==100]

Sanjay    100
Suman     100
dtype: int64

In [90]:
ser[ser<100]

Ajay     90
Ramya    89
John     68
dtype: int64

## DataFrame

In [134]:
dict1= {'Names':['Ajay','Sanjay','Ramya','Suman','John'],'Age':[22,23,24,30,32],'Gender':['Male','Male','Female','Female','Male'],'Location':['Bengaluru','Chennai','Bengaluru','Mumbai','Chennai']}

In [135]:
dict1

{'Names': ['Ajay', 'Sanjay', 'Ramya', 'Suman', 'John'],
 'Age': [22, 23, 24, 30, 32],
 'Gender': ['Male', 'Male', 'Female', 'Female', 'Male'],
 'Location': ['Bengaluru', 'Chennai', 'Bengaluru', 'Mumbai', 'Chennai']}

In [136]:
df= pd.DataFrame(dict1,index=range(1,6))
# df.set_index('Names')
df

Names  Age  Gender   Location
1    Ajay   22    Male  Bengaluru
2  Sanjay   23    Male    Chennai
3   Ramya   24  Female  Bengaluru
4   Suman   30  Female     Mumbai
5    John   32    Male    Chennai

In [137]:
df.columns

Index(['Names', 'Age', 'Gender', 'Location'], dtype='object')

In [138]:
df.shape

(5, 4)

In [139]:
df.size

20

In [140]:
df.ndim

2

In [141]:
df.Names

1      Ajay
2    Sanjay
3     Ramya
4     Suman
5      John
Name: Names, dtype: object

In [142]:
df[['Names','Age','Location']]

Names  Age   Location
1    Ajay   22  Bengaluru
2  Sanjay   23    Chennai
3   Ramya   24  Bengaluru
4   Suman   30     Mumbai
5    John   32    Chennai

In [143]:
df

Names  Age  Gender   Location
1    Ajay   22    Male  Bengaluru
2  Sanjay   23    Male    Chennai
3   Ramya   24  Female  Bengaluru
4   Suman   30  Female     Mumbai
5    John   32    Male    Chennai

In [144]:
df[0:3]

Names  Age  Gender   Location
1    Ajay   22    Male  Bengaluru
2  Sanjay   23    Male    Chennai
3   Ramya   24  Female  Bengaluru

In [145]:
df.iloc[:,:3]

Names  Age  Gender
1    Ajay   22    Male
2  Sanjay   23    Male
3   Ramya   24  Female
4   Suman   30  Female
5    John   32    Male

In [146]:
df.columns.get_loc('Gender')

2

In [147]:
df

Names  Age  Gender   Location
1    Ajay   22    Male  Bengaluru
2  Sanjay   23    Male    Chennai
3   Ramya   24  Female  Bengaluru
4   Suman   30  Female     Mumbai
5    John   32    Male    Chennai

In [148]:
df.iloc[:4,:3]

Names  Age  Gender
1    Ajay   22    Male
2  Sanjay   23    Male
3   Ramya   24  Female
4   Suman   30  Female

In [149]:
df.iloc[:4,[0,1,3]]

Names  Age   Location
1    Ajay   22  Bengaluru
2  Sanjay   23    Chennai
3   Ramya   24  Bengaluru
4   Suman   30     Mumbai

In [150]:
df

Names  Age  Gender   Location
1    Ajay   22    Male  Bengaluru
2  Sanjay   23    Male    Chennai
3   Ramya   24  Female  Bengaluru
4   Suman   30  Female     Mumbai
5    John   32    Male    Chennai

In [151]:
df.loc[1:4,'Names':'Gender']

Names  Age  Gender
1    Ajay   22    Male
2  Sanjay   23    Male
3   Ramya   24  Female
4   Suman   30  Female

In [152]:
df.loc[2:4,['Names','Age','Location']]

Names  Age   Location
2  Sanjay   23    Chennai
3   Ramya   24  Bengaluru
4   Suman   30     Mumbai

In [153]:
df.sort_values('Age',ascending=False)

Names  Age  Gender   Location
5    John   32    Male    Chennai
4   Suman   30  Female     Mumbai
3   Ramya   24  Female  Bengaluru
2  Sanjay   23    Male    Chennai
1    Ajay   22    Male  Bengaluru

In [132]:
# df.drop(columns=['Gender','Location'],inplace=True)

In [154]:
df.drop(columns=['Gender','Location'])

Names  Age
1    Ajay   22
2  Sanjay   23
3   Ramya   24
4   Suman   30
5    John   32

In [155]:
df

Names  Age  Gender   Location
1    Ajay   22    Male  Bengaluru
2  Sanjay   23    Male    Chennai
3   Ramya   24  Female  Bengaluru
4   Suman   30  Female     Mumbai
5    John   32    Male    Chennai

In [157]:
df[df.Gender=='Female']

Names  Age  Gender   Location
3  Ramya   24  Female  Bengaluru
4  Suman   30  Female     Mumbai

In [159]:
df[(df.Gender=='Male') & (df.Location=='Chennai')]

Names  Age Gender Location
2  Sanjay   23   Male  Chennai
5    John   32   Male  Chennai

In [160]:
df= pd.read_csv('CARS_1.csv')

In [161]:
df

name_of_car                    Model                             Type  \
0         Acura   NSX coupe 2dr manual S                           Sports   
1         Acura  3.5 RL w/Navigation 4dr                            Sedan   
2         Acura               3.5 RL 4dr                            Sedan   
3         Acura                      MDX                              NaN   
4         Acura                   TL 4dr                              NaN   
..          ...                      ...                              ...   
438         NaN                      NaN                              NaN   
439         NaN                      NaN                              NaN   
440         NaN                group by                1) data will split   
441         NaN                      NaN  2) apply the function mean(mpg)   
442         NaN                      NaN                       3) combine   

    Origin DriveTrain      MSRP   Invoice  EngineSize  Cylinders  Horsepower  \
0     Asia       Rear  $89,765   $79,978          3.2        6.0       290.0   
1     Asia      Front  $46,100   $41,100          3.5        6.0       225.0   
2     Asia      Front  $43,755   $39,014          3.5        6.0       225.0   
3     Asia        All  $36,945        NaN         3.5        6.0       265.0   
4     Asia      Front  $33,195        NaN         3.2        6.0       270.0   
..     ...        ...       ...       ...         ...        ...         ...   
438    NaN        NaN       NaN       NaN         NaN        NaN         NaN   
439    NaN        NaN       NaN       NaN         NaN        NaN         NaN   
440    NaN        NaN       NaN       NaN         NaN        NaN         NaN   
441    NaN        NaN       NaN       NaN         NaN        NaN         NaN   
442    NaN        NaN       NaN       NaN         NaN        NaN         NaN   

     MPG_City  MPG_Highway  Weight  Wheelbase  Length  Unnamed: 15  
0        17.0         24.0  3153.0      100.0   174.0          NaN  
1        18.0         24.0  3893.0      115.0   197.0          NaN  
2        18.0         24.0  3880.0      115.0   197.0          NaN  
3        17.0         23.0  4451.0      106.0   189.0          NaN  
4        20.0         28.0  3575.0      108.0   186.0          NaN  
..        ...          ...     ...        ...     ...          ...  
438       NaN          NaN     NaN        NaN     NaN          NaN  
439       NaN          NaN     NaN        NaN     NaN          NaN  
440       NaN          NaN     NaN        NaN     NaN          NaN  
441       NaN          NaN     NaN        NaN     NaN          NaN  
442       NaN          NaN     NaN        NaN     NaN          NaN  

[443 rows x 16 columns]

In [162]:
df.head()

name_of_car                    Model    Type Origin DriveTrain      MSRP  \
0       Acura   NSX coupe 2dr manual S  Sports   Asia       Rear  $89,765    
1       Acura  3.5 RL w/Navigation 4dr   Sedan   Asia      Front  $46,100    
2       Acura               3.5 RL 4dr   Sedan   Asia      Front  $43,755    
3       Acura                      MDX     NaN   Asia        All  $36,945    
4       Acura                   TL 4dr     NaN   Asia      Front  $33,195    

    Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0  $79,978          3.2        6.0       290.0      17.0         24.0  3153.0   
1  $41,100          3.5        6.0       225.0      18.0         24.0  3893.0   
2  $39,014          3.5        6.0       225.0      18.0         24.0  3880.0   
3       NaN         3.5        6.0       265.0      17.0         23.0  4451.0   
4       NaN         3.2        6.0       270.0      20.0         28.0  3575.0   

   Wheelbase  Length  Unnamed: 15  
0      100.0   174.0          NaN  
1      115.0   197.0          NaN  
2      115.0   197.0          NaN  
3      106.0   189.0          NaN  
4      108.0   186.0          NaN

In [163]:
df.tail()

name_of_car      Model                             Type Origin DriveTrain  \
438         NaN        NaN                              NaN    NaN        NaN   
439         NaN        NaN                              NaN    NaN        NaN   
440         NaN  group by                1) data will split    NaN        NaN   
441         NaN        NaN  2) apply the function mean(mpg)    NaN        NaN   
442         NaN        NaN                       3) combine    NaN        NaN   

    MSRP Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  \
438  NaN     NaN         NaN        NaN         NaN       NaN          NaN   
439  NaN     NaN         NaN        NaN         NaN       NaN          NaN   
440  NaN     NaN         NaN        NaN         NaN       NaN          NaN   
441  NaN     NaN         NaN        NaN         NaN       NaN          NaN   
442  NaN     NaN         NaN        NaN         NaN       NaN          NaN   

     Weight  Wheelbase  Length  Unnamed: 15  
438     NaN        NaN     NaN          NaN  
439     NaN        NaN     NaN          NaN  
440     NaN        NaN     NaN          NaN  
441     NaN        NaN     NaN          NaN  
442     NaN        NaN     NaN          NaN

In [164]:
df.columns

Index(['name_of_car', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP',
       'Invoice', 'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City',
       'MPG_Highway', 'Weight', 'Wheelbase', 'Length', 'Unnamed: 15'],
      dtype='object')

In [165]:
df.shape

(443, 16)

In [166]:
df.size

7088

In [167]:
df.ndim

2

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name_of_car  428 non-null    object 
 1   Model        429 non-null    object 
 2   Type         409 non-null    object 
 3   Origin       428 non-null    object 
 4   DriveTrain   428 non-null    object 
 5   MSRP         428 non-null    object 
 6   Invoice      406 non-null    object 
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   343 non-null    float64
 10  MPG_City     428 non-null    float64
 11  MPG_Highway  428 non-null    float64
 12  Weight       428 non-null    float64
 13  Wheelbase    428 non-null    float64
 14  Length       428 non-null    float64
 15  Unnamed: 15  2 non-null      float64
dtypes: float64(9), object(7)
memory usage: 55.5+ KB


In [169]:
df['name_of_car']

0      Acura
1      Acura
2      Acura
3      Acura
4      Acura
       ...  
438      NaN
439      NaN
440      NaN
441      NaN
442      NaN
Name: name_of_car, Length: 443, dtype: object

In [170]:
df[['name_of_car','Origin']]

name_of_car Origin
0         Acura   Asia
1         Acura   Asia
2         Acura   Asia
3         Acura   Asia
4         Acura   Asia
..          ...    ...
438         NaN    NaN
439         NaN    NaN
440         NaN    NaN
441         NaN    NaN
442         NaN    NaN

[443 rows x 2 columns]

In [171]:
df.iloc[:50,:5]

name_of_car                             Model    Type  Origin DriveTrain
0        Acura            NSX coupe 2dr manual S  Sports    Asia       Rear
1        Acura           3.5 RL w/Navigation 4dr   Sedan    Asia      Front
2        Acura                        3.5 RL 4dr   Sedan    Asia      Front
3        Acura                               MDX     NaN    Asia        All
4        Acura                            TL 4dr     NaN    Asia      Front
5        Acura                           TSX 4dr     NaN    Asia      Front
6        Acura                    RSX Type S 2dr     NaN    Asia      Front
7         Audi                          RS 6 4dr     NaN  Europe      Front
8         Audi                  A8 L Quattro 4dr     NaN  Europe        All
9         Audi                A6 4.2 Quattro 4dr     NaN  Europe        All
10        Audi                  S4 Avant Quattro     NaN  Europe        All
11        Audi                    S4 Quattro 4dr     NaN  Europe        All
12        Audi    A4 3.0 Quattro convertible 2dr     NaN  Europe        All
13        Audi          A6 2.7 Turbo Quattro 4dr     NaN  Europe        All
14        Audi            A4 3.0 convertible 2dr     NaN  Europe      Front
15        Audi              A6 3.0 Avant Quattro     NaN  Europe        All
16        Audi    TT 3.2 coupe 2dr (convertible)     NaN  Europe        All
17        Audi                A6 3.0 Quattro 4dr     NaN  Europe        All
18        Audi  TT 1.8 Quattro 2dr (convertible)     NaN  Europe        All
19        Audi                        A6 3.0 4dr     NaN  Europe      Front
20        Audi    TT 1.8 convertible 2dr (coupe)     NaN  Europe      Front
21        Audi            A41.8T convertible 2dr     NaN  Europe      Front
22        Audi           A4 3.0 Quattro 4dr auto     NaN  Europe        All
23        Audi         A4 3.0 Quattro 4dr manual     NaN  Europe        All
24        Audi                        A4 3.0 4dr     NaN  Europe      Front
25        Audi                       A4 1.8T 4dr   Sedan  Europe      Front
26         BMW                         745Li 4dr   Sedan  Europe       Rear
27         BMW                          745i 4dr   Sedan  Europe       Rear
28         BMW                M3 convertible 2dr  Sports  Europe       Rear
29         BMW                         545iA 4dr   Sedan  Europe       Rear
30         BMW                           X5 4.4i     SUV  Europe        All
31         BMW                      M3 coupe 2dr  Sports  Europe       Rear
32         BMW                          530i 4dr   Sedan  Europe       Rear
33         BMW             330Ci convertible 2dr   Sedan  Europe       Rear
34         BMW           Z4 convertible 3.0i 2dr  Sports  Europe       Rear
35         BMW                          525i 4dr   Sedan  Europe       Rear
36         BMW             325Ci convertible 2dr   Sedan  Europe       Rear
37         BMW                         330xi 4dr   Sedan  Europe        All
38         BMW                         330Ci 2dr   Sedan  Europe       Rear
39         BMW                           X3 3.0i     SUV  Europe        All
40         BMW                          330i 4dr   Sedan  Europe       Rear
41         BMW           Z4 convertible 2.5i 2dr  Sports  Europe       Rear
42         BMW                       325xi Sport   Wagon  Europe        All
43         BMW                         325Ci 2dr   Sedan  Europe       Rear
44         BMW                         325xi 4dr   Sedan  Europe        All
45         BMW                          325i 4dr   Sedan  Europe       Rear
46       Buick             Park Avenue Ultra 4dr   Sedan     USA      Front
47       Buick                           Rainier     SUV     USA        All
48       Buick                   Park Avenue 4dr   Sedan     USA      Front
49       Buick               LeSabre Limited 4dr   Sedan     USA      Front

In [172]:
df['name_of_car'].unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hummer', 'Hyundai',
       'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
       'Lexus', 'Lincoln', 'Mazda', 'Mercedes-Benz', 'Mercury', 'MINI',
       'Mitsubishi', 'Nissan', 'Oldsmobile', 'Pontiac', 'Porsche', 'Saab',
       'Saturn', 'Scion', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen',
       'Volvo', nan], dtype=object)

In [174]:
df['Origin'].unique()

array(['Asia', 'Europe', 'USA', nan], dtype=object)

In [175]:
df['Origin'].value_counts()

Origin
Asia      158
USA       147
Europe    123
Name: count, dtype: int64

In [173]:
df['name_of_car'].value_counts()

name_of_car
Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Volvo            12
Jaguar           12
Hyundai          12
Subaru           11
Pontiac          11
Mazda            11
Lexus            11
Kia              11
Buick             9
Mercury           9
Lincoln           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: count, dtype: int64

In [176]:
pd.crosstab(index=df['Origin'],columns=df['name_of_car'])

name_of_car  Acura  Audi  BMW  Buick  Cadillac  Chevrolet  Chrysler  Dodge  \
Origin                                                                       
Asia             7     0    0      0         0          0         0      0   
Europe           0    19   20      0         0          0         0      0   
USA              0     0    0      9         8         27        15     13   

name_of_car  Ford  GMC  ...  Pontiac  Porsche  Saab  Saturn  Scion  Subaru  \
Origin                  ...                                                  
Asia            0    0  ...        0        0     0       0      2      11   
Europe          0    0  ...        0        7     7       0      0       0   
USA            23    8  ...       11        0     0       8      0       0   

name_of_car  Suzuki  Toyota  Volkswagen  Volvo  
Origin                                          
Asia              8      28           0      0  
Europe            0       0          15     12  
USA               0       0           0      0  

[3 rows x 38 columns]

In [177]:
pd.crosstab(index=[df['Origin'],df['Type']],columns=df['name_of_car'])

name_of_car    Acura  Audi  BMW  Buick  Cadillac  Chevrolet  Chrysler  Dodge  \
Origin Type                                                                    
Asia   Hybrid      0     0    0      0         0          0         0      0   
       SUV         0     0    0      0         0          0         0      0   
       Sedan       2     0    0      0         0          0         0      0   
       Sports      1     0    0      0         0          0         0      0   
       Truck       0     0    0      0         0          0         0      0   
       Wagon       0     0    0      0         0          0         0      0   
Europe SUV         0     0    2      0         0          0         0      0   
       Sedan       0     1   13      0         0          0         0      0   
       Sports      0     0    4      0         0          0         0      0   
       Wagon       0     0    1      0         0          0         0      0   
USA    SUV         0     0    0      2         2          4         0      1   
       Sedan       0     0    0      7         4         15        13      8   
       Sports      0     0    0      0         1          2         1      1   
       Truck       0     0    0      0         1          5         0      3   
       Wagon       0     0    0      0         0          1         1      0   

name_of_car    Ford  GMC  ...  Pontiac  Porsche  Saab  Saturn  Scion  Subaru  \
Origin Type               ...                                                  
Asia   Hybrid     0    0  ...        0        0     0       0      0       0   
       SUV        0    0  ...        0        0     0       0      0       0   
       Sedan      0    0  ...        0        0     0       0      1       6   
       Sports     0    0  ...        0        0     0       0      0       2   
       Truck      0    0  ...        0        0     0       0      0       1   
       Wagon      0    0  ...        0        0     0       0      1       2   
Europe SUV        0    0  ...        0        1     0       0      0       0   
       Sedan      0    0  ...        0        0     6       0      0       0   
       Sports     0    0  ...        0        6     0       0      0       0   
       Wagon      0    0  ...        0        0     1       0      0       0   
USA    SUV        4    3  ...        1        0     0       1      0       0   
       Sedan     11    1  ...        8        0     0       6      0       0   
       Sports     3    0  ...        1        0     0       0      0       0   
       Truck      3    4  ...        0        0     0       0      0       0   
       Wagon      2    0  ...        1        0     0       1      0       0   

name_of_car    Suzuki  Toyota  Volkswagen  Volvo  
Origin Type                                       
Asia   Hybrid       0       1           0      0  
       SUV          2       5           0      0  
       Sedan        5      16           0      0  
       Sports       0       2           0      0  
       Truck        0       3           0      0  
       Wagon        1       1           0      0  
Europe SUV          0       0           1      1  
       Sedan        0       0          11      9  
       Sports       0       0           0      0  
       Wagon        0       0           3      2  
USA    SUV          0       0           0      0  
       Sedan        0       0           0      0  
       Sports       0       0           0      0  
       Truck        0       0           0      0  
       Wagon        0       0           0      0  

[15 rows x 38 columns]

In [181]:
df[['Origin','EngineSize']]

Origin  EngineSize
0     Asia         3.2
1     Asia         3.5
2     Asia         3.5
3     Asia         3.5
4     Asia         3.2
..     ...         ...
438    NaN         NaN
439    NaN         NaN
440    NaN         NaN
441    NaN         NaN
442    NaN         NaN

[443 rows x 2 columns]

In [179]:
df.groupby('Origin')['EngineSize'].max()

Origin
Asia      5.6
Europe    6.0
USA       8.3
Name: EngineSize, dtype: float64

In [180]:
df.groupby('Origin')['EngineSize'].mean()

Origin
Asia      2.774051
Europe    3.206504
USA       3.642857
Name: EngineSize, dtype: float64

In [189]:
df.groupby(['Origin','Type'])[['EngineSize','Weight']].agg([max,min,'mean','median'])

EngineSize                        Weight                       \
                     max  min      mean median     max     min         mean   
Origin Type                                                                   
Asia   Hybrid        2.0  1.4  1.633333   1.50  2890.0  1850.0  2490.666667   
       SUV           5.6  2.0  3.470833   3.40  5590.0  3020.0  4093.750000   
       Sedan         4.5  1.5  2.651648   2.50  4802.0  2035.0  3160.285714   
       Sports        4.3  1.3  2.452941   2.20  3840.0  2195.0  3009.764706   
       Truck         5.6  2.3  3.362500   3.35  5287.0  2750.0  3793.125000   
       Wagon         4.5  1.5  2.645455   2.50  4309.0  2425.0  3236.272727   
Europe SUV           5.0  2.5  3.950000   4.40  5423.0  3577.0  4735.000000   
       Sedan         6.0  1.6  3.034848   2.85  5399.0  2524.0  3578.969697   
       Sports        5.5  2.3  3.710526   3.60  4429.0  2811.0  3481.210526   
       Wagon         5.0  1.8  2.780000   2.50  4230.0  2822.0  3596.400000   
USA    SUV           6.8  2.2  4.356000   4.20  7190.0  2866.0  4664.600000   
       Sedan         4.6  1.6  3.234444   3.40  4605.0  2348.0  3461.244444   
       Sports        8.3  3.2  5.055556   4.60  3780.0  3060.0  3417.000000   
       Truck         6.0  2.3  4.437500   4.45  5879.0  3028.0  4479.562500   
       Wagon         3.5  1.8  2.714286   3.00  4675.0  2701.0  3375.714286   

                       
               median  
Origin Type            
Asia   Hybrid  2732.0  
       SUV     3985.0  
       Sedan   3255.0  
       Sports  3085.0  
       Truck   3748.0  
       Wagon   3090.0  
Europe SUV     4849.0  
       Sedan   3481.5  
       Sports  3240.0  
       Wagon   3607.0  
USA    SUV     4600.0  
       Sedan   3472.5  
       Sports  3347.0  
       Truck   4545.0  
       Wagon   3458.0

In [190]:
import warnings
warnings.filterwarnings('ignore')

In [193]:
df.pivot_table(index=['name_of_car','Type'],columns='Origin',values='Weight',aggfunc=(['max','min','mean','median']))

max                 min                mean  \
Origin                Asia  Europe USA    Asia  Europe USA    Asia   
name_of_car Type                                                     
Acura       Sedan   3893.0     NaN NaN  3880.0     NaN NaN  3886.5   
            Sports  3153.0     NaN NaN  3153.0     NaN NaN  3153.0   
Audi        Sedan      NaN  3252.0 NaN     NaN  3252.0 NaN     NaN   
BMW         Sedan      NaN  4464.0 NaN     NaN  3197.0 NaN     NaN   
            Sports     NaN  3781.0 NaN     NaN  2932.0 NaN     NaN   
...                    ...     ...  ..     ...     ...  ..     ...   
Volkswagen  SUV        NaN  5086.0 NaN     NaN  5086.0 NaN     NaN   
            Wagon      NaN  4067.0 NaN     NaN  3034.0 NaN     NaN   
Volvo       Sedan      NaN  3903.0 NaN     NaN  2767.0 NaN     NaN   
            SUV        NaN  4638.0 NaN     NaN  4638.0 NaN     NaN   
            Wagon      NaN  3823.0 NaN     NaN  2822.0 NaN     NaN   

                                     median              
Origin                   Europe USA    Asia  Europe USA  
name_of_car Type                                         
Acura       Sedan           NaN NaN  3886.5     NaN NaN  
            Sports          NaN NaN  3153.0     NaN NaN  
Audi        Sedan   3252.000000 NaN     NaN  3252.0 NaN  
BMW         Sedan   3589.230769 NaN     NaN  3472.0 NaN  
            Sports  3281.500000 NaN     NaN  3206.5 NaN  
...                         ...  ..     ...     ...  ..  
Volkswagen  SUV     5086.000000 NaN     NaN  5086.0 NaN  
            Wagon   3479.666667 NaN     NaN  3338.0 NaN  
Volvo       Sedan   3536.333333 NaN     NaN  3576.0 NaN  
            SUV     4638.000000 NaN     NaN  4638.0 NaN  
            Wagon   3322.500000 NaN     NaN  3322.5 NaN  

[111 rows x 12 columns]